version: '3.8'

services:
  pve-dashboard:
    image: stessmann/proxmox-unified-console:latest
    container_name: puc_dashboard
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443" 
    volumes:
      - ./data:/var/www/data
    environment:
      - TZ=Europe/Berlin